[serve.static]
env = "BUN_PUBLIC_*"
plugins = ["bun-plugin-tailwind"]
[install]
registry = "https://registry.npmjs.org" # Sets the default registry
# registry = { url = "https://registry.npmjs.org", token = "YOUR_AUTH_TOKEN" } # With a token
